## Working with date and time

In [122]:
import pandas as pd
import numpy as np

In [123]:
date = pd.read_csv("../../Datasets/orders.csv")
time = pd.read_csv("../../Datasets/messages.csv")

In [124]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [125]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [126]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [127]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [128]:
date['date'] = pd.to_datetime(date['date'])

In [129]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## Working With Dates

### Extracting Dates

In [130]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

### Extracting Months

In [131]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

### Extracting Months_Name

In [132]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

### Extract Days

In [133]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [134]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [135]:
date.drop(columns=['product_id','city_id','orders'])

          date  date_year  date_month_no date_month_name  date_day  date_dow
0   2019-12-10       2019             12        December        10         1
1   2018-08-15       2018              8          August        15         2
2   2018-10-23       2018             10         October        23         1
3   2019-08-17       2019              8          August        17         5
4   2019-01-06       2019              1         January         6         6
..         ...        ...            ...             ...       ...       ...
995 2018-10-08       2018             10         October         8         0
996 2018-12-06       2018             12        December         6         3
997 2019-05-07       2019              5             May         7         1
998 2019-03-03       2019              3           March         3         6
999 2019-10-15       2019             10         October        15         1

[1000 rows x 6 columns]

In [136]:
date['date_dow_name'] = date['date'].dt.day_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
489,2018-12-02,3247,0,3,2018,12,December,2,6,Sunday
109,2018-08-08,351,20,1,2018,8,August,8,2,Wednesday
940,2019-03-02,7208,6,1,2019,3,March,2,5,Saturday
400,2019-04-18,5119,0,1,2019,4,April,18,3,Thursday
623,2018-09-13,4597,3,2,2018,9,September,13,3,Thursday

In [137]:
# is weekend?
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Saturday','Sunday']),1,0)
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

In [138]:
date['date_week'] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

In [139]:
date['date_quarter'] = date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,date_quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

In [140]:
date['date_semester'] = np.where(date['date_quarter'].isin([1,2]),1,2)
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,date_quarter,date_semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

### Extract Time elapsed between dates

In [141]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 2, 18, 22, 19, 27, 336288)

In [142]:
today - date['date']

0     2262 days 22:19:27.336288
1     2744 days 22:19:27.336288
2     2675 days 22:19:27.336288
3     2377 days 22:19:27.336288
4     2600 days 22:19:27.336288
                 ...
995   2690 days 22:19:27.336288
996   2631 days 22:19:27.336288
997   2479 days 22:19:27.336288
998   2544 days 22:19:27.336288
999   2318 days 22:19:27.336288
Name: date, Length: 1000, dtype: timedelta64[ns]

In [143]:
(today - date['date']).dt.days

0      2262
1      2744
2      2675
3      2377
4      2600
       ...
995    2690
996    2631
997    2479
998    2544
999    2318
Name: date, Length: 1000, dtype: int64

In [144]:
np.round((today - date['date']) / np.timedelta64(30, 'D'), 0)

0      75.0
1      91.0
2      89.0
3      79.0
4      87.0
       ...
995    90.0
996    88.0
997    83.0
998    85.0
999    77.0
Name: date, Length: 1000, dtype: float64

In [145]:
time['date'] = pd.to_datetime(time['date'])

In [146]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [147]:
time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [148]:
time['hour'] = time['date'].dt.hour
time['minute'] = time['date'].dt.minute
time['second'] = time['date'].dt.second
time.head()

,date,msg,hour,minute,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [149]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,minute,second,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [150]:
today - time['date']

0     4448 days 21:29:27.336288
1     4312 days 22:39:27.336288
2     4798 days 21:58:27.336288
3     4100 days 21:48:27.336288
4     4497 days 23:08:27.336288
                 ...
995   5087 days 21:29:27.336288
996   4408 days 23:05:27.336288
997   4873 days 22:42:27.336288
998   4989 days 22:45:27.336288
999   4261 days 22:54:27.336288
Name: date, Length: 1000, dtype: timedelta64[ns]

In [151]:
(today - time['date'])/np.timedelta64(1,'s')

0      3.843846e+08
1      3.726384e+08
2      4.146263e+08
3      3.543185e+08
4      3.886241e+08
           ...
995    4.395942e+08
996    3.809343e+08
997    4.211089e+08
998    4.311315e+08
999    3.682329e+08
Name: date, Length: 1000, dtype: float64

In [152]:
# in minutes
(today - time['date'])/np.timedelta64(1,'m')

0      6.406409e+06
1      6.210639e+06
2      6.910438e+06
3      5.905308e+06
4      6.477068e+06
           ...
995    7.326569e+06
996    6.348905e+06
997    7.018482e+06
998    7.185525e+06
999    6.137214e+06
Name: date, Length: 1000, dtype: float64

In [153]:
# in hours
(today - time['date'])/np.timedelta64(1,'h')

0      106773.490927
1      103510.657593
2      115173.974260
3       98421.807593
4      107951.140927
           ...
995    122109.490927
996    105815.090927
997    116974.707593
998    119758.757593
999    102286.907593
Name: date, Length: 1000, dtype: float64