### Loading DataFrames from Files

In [1]:
import pandas as pd

In [2]:
coffee = pd.read_csv("./1.Instructors_Tutorial/warmup-data/coffee.csv")

In [3]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [4]:
# Gives random values
coffee.sample(5)

          Day Coffee Type  Units Sold
1      Monday       Latte          15
12     Sunday    Espresso          45
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
10   Saturday    Espresso          45

In [5]:
# Give random values but only give fixed values no matter how many times you run
coffee.sample(5, random_state=1)

         Day Coffee Type  Units Sold
3    Tuesday       Latte          20
7   Thursday       Latte          30
6   Thursday    Espresso          40
2    Tuesday    Espresso          30
10  Saturday    Espresso          45

### Accessing Data with Pandas

In [14]:
# Loc is used for accessing elements by rows and columns
# Selecting single row
coffee.loc[[0]]

      Day Coffee Type  Units Sold
0  Monday    Espresso          25

In [7]:
# To select multiple elements
coffee.loc[[0,4,2]]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
4  Wednesday    Espresso          35
2    Tuesday    Espresso          30

In [8]:
# Slicing to get elements
coffee.loc[8:14]

         Day Coffee Type  Units Sold
8     Friday    Espresso          45
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [9]:
# Selecting a single column
# coffee["Day"]
# coffee.loc[ : ,'Day']
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [10]:
# To get a single element using row and column
coffee.loc[3,'Day']

'Tuesday'

In [11]:
# To get multiple rows and specific columns
coffee.loc[5:11, ["Day","Coffee Type"]]

          Day Coffee Type
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte

In [12]:
# Using slicing to get values
coffee.loc[6:9 , "Coffee Type":"Units Sold"]

  Coffee Type  Units Sold
6    Espresso          40
7       Latte          30
8    Espresso          45
9       Latte          35

In [13]:
# Similarly you can do all these operations for Iloc
# Iloc is basically accessing elements using index like in arrays unlike in Loc
# In loc it is accessed by name of the index and the column