### Modifying Data with Pandas

In [12]:
import pandas as pd

In [13]:
coffee = pd.read_csv("./1.Instructors_Tutorial/warmup-data/coffee.csv")

In [14]:
# Taking a column and changing index values according to it for example-
# coffee.index = coffee.Day
# coffee.head()

In [15]:
# So now what we can do is access all Monday with loc
# coffee.loc["Monday"]

In [16]:
# Also do slicing on it .. to get values from 
# Monday(First Monday seen)to Wednesday(Last Wednesday seen)
# coffee.loc["Monday":"Wednesday", ["Units Sold"]]

In [17]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [18]:
# Can also modify values
coffee.loc[1,"Units Sold"] = 10
# Can also modify multiple values using slicing
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [19]:
# sort_values sorts in ascending order by default
# syntax: dataframe.sort_values("column", ascending = True(by default)/False)
coffee.sort_values("Units Sold", ascending=False)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [20]:
# Simple rule: Place bracket for multiple values
coffee.sort_values(["Units Sold","Coffee Type"], ascending=[False,True])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          10