### Adding and Removing Columns

In [1]:
import pandas as pd

In [ ]:
coffee = pd.read_csv("./data/coffee.csv")

In [3]:
# Write now you can see toffee is is also using same data as coffee
# Meaning if you change toffee or coffee both will change
# coffee["Price"] = 4.99
toffee = coffee

In [4]:
# so we do toffee.copy() to create a fresh copy and now both are independent
toffee = coffee.copy()

In [5]:
# You can create a new column like this
coffee["Price"] = 4.99

In [6]:
coffee.head()

         Day Coffee Type  Units Sold  Price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [7]:
import numpy as np
coffee["New_Prices"] = np.where(coffee["Coffee Type"] == "Espresso",3.99,5.99)
coffee.head()

         Day Coffee Type  Units Sold  Price  New_Prices
0     Monday    Espresso          25   4.99        3.99
1     Monday       Latte          15   4.99        5.99
2    Tuesday    Espresso          30   4.99        3.99
3    Tuesday       Latte          20   4.99        5.99
4  Wednesday    Espresso          35   4.99        3.99

In [8]:
# To drop a row
coffee.drop(0)

          Day Coffee Type  Units Sold  Price  New_Prices
1      Monday       Latte          15   4.99        5.99
2     Tuesday    Espresso          30   4.99        3.99
3     Tuesday       Latte          20   4.99        5.99
4   Wednesday    Espresso          35   4.99        3.99
5   Wednesday       Latte          25   4.99        5.99
6    Thursday    Espresso          40   4.99        3.99
7    Thursday       Latte          30   4.99        5.99
8      Friday    Espresso          45   4.99        3.99
9      Friday       Latte          35   4.99        5.99
10   Saturday    Espresso          45   4.99        3.99
11   Saturday       Latte          35   4.99        5.99
12     Sunday    Espresso          45   4.99        3.99
13     Sunday       Latte          35   4.99        5.99

In [9]:
# To drop a column there are two options
# coffee.drop("Price" ,axis = 1)
# if you add inplace = True then it will
# permanently delete the row or column from the data
coffee.drop(columns = "Price")

          Day Coffee Type  Units Sold  New_Prices
0      Monday    Espresso          25        3.99
1      Monday       Latte          15        5.99
2     Tuesday    Espresso          30        3.99
3     Tuesday       Latte          20        5.99
4   Wednesday    Espresso          35        3.99
5   Wednesday       Latte          25        5.99
6    Thursday    Espresso          40        3.99
7    Thursday       Latte          30        5.99
8      Friday    Espresso          45        3.99
9      Friday       Latte          35        5.99
10   Saturday    Espresso          45        3.99
11   Saturday       Latte          35        5.99
12     Sunday    Espresso          45        3.99
13     Sunday       Latte          35        5.99

In [10]:
toffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [11]:
coffee = coffee.drop(columns="Price")

In [12]:
coffee["Revenue"] = coffee["Units Sold"]*coffee["New_Prices"]

In [13]:
coffee.head()

         Day Coffee Type  Units Sold  New_Prices  Revenue
0     Monday    Espresso          25        3.99    99.75
1     Monday       Latte          15        5.99    89.85
2    Tuesday    Espresso          30        3.99   119.70
3    Tuesday       Latte          20        5.99   119.80
4  Wednesday    Espresso          35        3.99   139.65

In [14]:
coffee.rename(columns={"New_Prices":"Prices"},inplace=True)

In [15]:
coffee

          Day Coffee Type  Units Sold  Prices  Revenue
0      Monday    Espresso          25    3.99    99.75
1      Monday       Latte          15    5.99    89.85
2     Tuesday    Espresso          30    3.99   119.70
3     Tuesday       Latte          20    5.99   119.80
4   Wednesday    Espresso          35    3.99   139.65
5   Wednesday       Latte          25    5.99   149.75
6    Thursday    Espresso          40    3.99   159.60
7    Thursday       Latte          30    5.99   179.70
8      Friday    Espresso          45    3.99   179.55
9      Friday       Latte          35    5.99   209.65
10   Saturday    Espresso          45    3.99   179.55
11   Saturday       Latte          35    5.99   209.65
12     Sunday    Espresso          45    3.99   179.55
13     Sunday       Latte          35    5.99   209.65