### Adding & Removing Columns

In [36]:
import pandas as pd

In [ ]:
bio = pd.read_csv("./data/bios.csv")
bios = bio.copy()

In [38]:
bios["first_name"] = bios["name"].str.split(' ').str[0]

In [39]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0

In [40]:
bios["born_datetime"] = pd.to_datetime(bios["born_date"])

In [41]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0

In [42]:
# As you can see born_datetime column that is just created has datetime64 Data type
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  object
 2   born_date      143693 non-null  object
 3   born_city      110908 non-null  object
 4   born_region    110908 non-null  object
 5   born_country   110908 non-null  object
 6   NOC            145499 non-null  object
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   object
 10  first_name     145500 non-null  object
 11  born_datetime  143693 non-null  datetime64[ns]
 12  year           143693 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(8)
memory usage: 14.4+ MB

In [43]:
bios["year"] = bios["born_datetime"].dt.year

In [44]:
bios[["first_name","year"]].head()

      first_name    year
0  Jean-François  1886.0
1         Arnaud  1969.0
2           Jean  1898.0
3        Jacques  1895.0
4         Albert  1878.0

In [ ]:
bio.to_csv("./data/bios.csv",index = False)
# This will remove index values in the original saved csv just for users sake

In [48]:
# Applying lambda function 
bios["height_category"] = bios["height_cm"].apply(lambda x : 'Short' if x < 145 else "Average" if x < 170 else "Tall")

In [52]:
bios[['height_category']].head()

  height_category
0            Tall
1            Tall
2            Tall
3         Average
4            Tall