### Merging & Concatenating Data

In [67]:
import pandas as pd

In [68]:
df = pd.read_csv("./1.Instructors_Tutorial/data/bios.csv")
bios = df.copy();
noc = pd.read_csv("./1.Instructors_Tutorial/data/noc_regions.csv")

In [69]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0

In [70]:

noc.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [71]:
# So what we did basically is merged two different datasets left_on is the column 
# which is present in bios and right_one is in noc one and we are merging two of them
# how by inner join meaning the values which are common in both the selected columns
# will only be there

# for example there is left_inner join it joins basis of what values are present in the
# left column/dataset if it has row 1 2 4 but right one has 1 2 3 
# so the resultant row will be 1 2 4 and 4th row will be having null column values 
# will ignore any extra rows in right one

# simmillarly right_inner join
# outer join is there which just combines all the values of both the columns 
# regardless of whether they are present in left, right column or not
# if there are not present null will be filled
bios = pd.merge(bios, noc, left_on="born_country", right_on="NOC", how="inner")

In [72]:
bios.head(5)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,first_name,born_datetime,year,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,GBR,UK,NaN

In [73]:
bios=bios.drop(["born_country","notes"], axis=1)
bios.head(4)

,athlete_id,name,born_date,born_city,born_region,NOC_x,height_cm,weight_kg,died_date,first_name,born_datetime,year,NOC_y,region
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,FRA,France
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,FRA,France
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,FRA,France
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,FRA,France

In [74]:
bios = bios.rename(columns={"NOC_x":"Country", "NOC_y":"Country_Code"})
bios.head(4)

,athlete_id,name,born_date,born_city,born_region,Country,height_cm,weight_kg,died_date,first_name,born_datetime,year,Country_Code,region
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,FRA,France
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,FRA,France
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,FRA,France
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,FRA,France

In [75]:
# these get the rows based on these two column where values are not equal
bios[(bios["Country"]) != bios["region"]][["name","Country","region"]].head()

                 name        Country   region
4        Albert Canet         France       UK
14         Guy Forget         France  Morocco
32    Helen Aitchison  Great Britain       UK
33  Geraldine Beamish  Great Britain       UK
34       Dora Boothby  Great Britain       UK

In [84]:
usa = bios[bios["Country_Code"]=="FRA"].copy()
gbr = bios[bios["region"]=="Germany"].copy()

In [ ]:
new_df = pd.concat([usa,gbr])

In [89]:
new_df.tail(5)

,athlete_id,name,born_date,born_city,born_region,Country,height_cm,weight_kg,died_date,first_name,born_datetime,year,Country_Code,region
110043,148447,Felix Rijhnen,1990-07-09,Darmstadt,Hessen,Germany,NaN,NaN,NaN,Felix,1990-07-09,1990.0,GER,Germany
110351,148873,Katharina Wick,1996-11-15,Unna,Nordrhein-Westfalen,Romania,175.0,67.0,NaN,Katharina,1996-11-15,1996.0,GER,Germany
110381,148917,Niklas Hartweg,2000-03-01,Karlsruhe,Baden-Württemberg,Switzerland,NaN,NaN,NaN,Niklas,2000-03-01,2000.0,GER,Germany
110605,149178,Julian Rauchfuss,1994-09-02,Mindelheim,Bayern,Germany,NaN,NaN,NaN,Julian,1994-09-02,1994.0,GER,Germany
110623,149199,Tobias Schneider,1992-07-02,Roth,Bayern,Germany,NaN,NaN,NaN,Tobias,1992-07-02,1992.0,GER,Germany

In [90]:
results = pd.read_csv("./1.Instructors_Tutorial/data/results.csv")

In [94]:
bios.head(5)

,athlete_id,name,born_date,born_city,born_region,Country,height_cm,weight_kg,died_date,first_name,born_datetime,year,Country_Code,region
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,FRA,France
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,FRA,France
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,FRA,France
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,FRA,France
4,5,Albert Canet,1878-04-17,Wandsworth,England,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,GBR,UK

In [95]:
new_merge = pd.merge(results,bios, on="athlete_id", how="left")

In [96]:
new_merge.head()

,year_x,type,discipline,event,as,athlete_id,noc,team,place,tied,...,born_region,Country,height_cm,weight_kg,died_date,first_name,born_datetime,year_y,Country_Code,region
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,Gironde,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,FRA,France
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,Gironde,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,FRA,France
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,Gironde,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,FRA,France
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,Gironde,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,FRA,France
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,Gironde,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,FRA,France