## Aggregating Data

In [39]:
import pandas as pd

In [ ]:
df = pd.read_csv("./data/bios.csv")
coffee = pd.read_csv("./data/coffee.csv")

In [41]:
df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0

In [42]:
# Value counts is used for finding what values/categories are the most frequent ones
df["born_city"].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Kirovgrad             1
Pereiaslav            1
Podgornyy             1
Kudepsta              1
Furmanov              1
Name: count, Length: 22368, dtype: int64

In [43]:
df[df["born_country"]=="USA"]["born_city"].value_counts()

born_city
New York         416
Chicago          283
Los Angeles      230
Philadelphia     205
Boston           153
                ...
Milpitas           1
Chesterfield       1
American Fork      1
Cadyville          1
Fair Haven         1
Name: count, Length: 2255, dtype: int64

In [44]:
df.groupby("born_country")["height_cm"].mean()

born_country
AFG       170.416667
AGU       186.000000
ALB       174.657895
ALG       176.489362
AND       172.096774
             ...
VIN       181.200000
Vienna    171.000000
YEM       169.000000
ZAM       173.192308
ZIM       173.540000
Name: height_cm, Length: 236, dtype: float64

In [45]:
coffee.groupby("Coffee Type")["Units Sold"].sum()

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [46]:
coffee.groupby("Coffee Type").agg({"Units Sold":"sum","Day":"count"})

             Units Sold  Day
Coffee Type
Espresso            265    7
Latte               195    7

In [47]:
coffee.groupby(["Coffee Type","Day"]).agg({"Units Sold":"sum","Day":"count"})

                       Units Sold  Day
Coffee Type Day
Espresso    Friday             45    1
            Monday             25    1
            Saturday           45    1
            Sunday             45    1
            Thursday           40    1
            Tuesday            30    1
            Wednesday          35    1
Latte       Friday             35    1
            Monday             15    1
            Saturday           35    1
            Sunday             35    1
            Thursday           30    1
            Tuesday            20    1
            Wednesday          25    1

In [48]:
df = pd.DataFrame({
    "user_id": [1, 1, 1, 2, 2, 3],
    "product": ["A", "B", "A", "A", "C", "B"],
    "price": [10, 20, 15, 10, 30, 20],
    "quantity": [1, 2, 1, 3, 1, 2]
})

In [49]:

print(df.groupby("user_id")["product"].value_counts())
print(df.groupby("user_id")["price"].count())
print(df.groupby("user_id")["price"].sum())

user_id  product
1        A          2
         B          1
2        A          1
         C          1
3        B          1
Name: count, dtype: int64
user_id
1    3
2    2
3    1
Name: price, dtype: int64
user_id
1    45
2    40
3    20
Name: price, dtype: int64

In [50]:
print(df.groupby("user_id")["price"].max())
print(df.groupby("user_id")["price"].min())

user_id
1    20
2    30
3    20
Name: price, dtype: int64
user_id
1    10
2    10
3    20
Name: price, dtype: int64

In [ ]:
df.head()

   user_id product  price  quantity
0        1       A     10         1
1        1       B     20         2
2        1       A     15         1
3        2       A     10         3
4        2       C     30         1

In [52]:

df.groupby("user_id")["price"].agg(["sum","mean","max","min"])

         sum  mean  max  min
user_id
1         45  15.0   20   10
2         40  20.0   30   10
3         20  20.0   20   20

In [53]:
df.groupby("user_id").agg(avg_price = ("price","mean"), product_quantity=("quantity", "sum"),counting=("product","unique"))

         avg_price  product_quantity counting
user_id
1             15.0                 4   [A, B]
2             20.0                 4   [A, C]
3             20.0                 2      [B]

In [67]:
df.groupby(["user_id","product"])["price"].sum()

user_id  product
1        A          25
         B          20
2        A          10
         C          30
3        B          20
Name: price, dtype: int64

In [70]:
df.groupby("user_id")["price"].transform("sum")

0    45
1    45
2    45
3    40
4    40
5    20
Name: price, dtype: int64